package org.apache.seatunnel.web.engine.client.modal;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.apache.seatunnel.web.common.enums.JobStatus;


@Getter
@AllArgsConstructor
public class ZetaJobStatusResolveResult {

    /**
     * Whether the engine job was found from Zeta.
     */
    private final boolean found;

    /**
     * Whether the engine job is still running.
     */
    private final boolean running;

    /**
     * Local job status mapped from Zeta status.
     */
    private final JobStatus localStatus;

    /**
     * Raw engine status.
     */
    private final String engineStatus;

    /**
     * Error message returned by Zeta or generated by resolver.
     */
    private final String errorMessage;

    /**
     * Human-readable resolve message.
     */
    private final String message;

    public static ZetaJobStatusResolveResult running(String engineStatus) {
        return new ZetaJobStatusResolveResult(
                true,
                true,
                JobStatus.RUNNING,
                engineStatus == null ? "RUNNING" : engineStatus,
                null,
                "Zeta job is still running"
        );
    }

    public static ZetaJobStatusResolveResult finished(JobStatus status,
                                                      String engineStatus,
                                                      String errorMessage,
                                                      String message) {
        return new ZetaJobStatusResolveResult(
                true,
                false,
                status,
                engineStatus,
                errorMessage,
                message
        );
    }

    public static ZetaJobStatusResolveResult notFound(String message) {
        return new ZetaJobStatusResolveResult(
                false,
                false,
                JobStatus.FAILED,
                "NOT_FOUND",
                message,
                message
        );
    }

    public static ZetaJobStatusResolveResult unknown(String message) {
        return new ZetaJobStatusResolveResult(
                false,
                false,
                JobStatus.UNKNOWABLE,
                "UNKNOWN",
                message,
                message
        );
    }
}
